.TH OROBORUS 5
.SH NAME
oroborusrc \- oroborus(1) configuration file.
.br
.SH "DESCRIPTION"
.PP
The
.B Oroborusrc
is the main configuration file for
.BR oroborus(1).

You can have an
.B /usr/share/oroborus/defaults
for the global configuration of
.BR oroborus(1)
.BR and an
.BR $HOME/.oroborusrc
for a per user configuration of
.BR oroborus(1).

.SH "SEE ALSO"
oroborus(1) deskmenu(1) desklaunch(1) keylaunch(1) idesk(1) dfm(1)
.SH AUTHOR
This manual page was written by Stefan Pfetzing <dreamind@dreamind.de>.
